###################################################################

# Created by write_sdc on Sun Nov 30 07:59:13 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_load -pin_load 1 [get_ports {store_data[31]}]
set_load -pin_load 1 [get_ports {store_data[30]}]
set_load -pin_load 1 [get_ports {store_data[29]}]
set_load -pin_load 1 [get_ports {store_data[28]}]
set_load -pin_load 1 [get_ports {store_data[27]}]
set_load -pin_load 1 [get_ports {store_data[26]}]
set_load -pin_load 1 [get_ports {store_data[25]}]
set_load -pin_load 1 [get_ports {store_data[24]}]
set_load -pin_load 1 [get_ports {store_data[23]}]
set_load -pin_load 1 [get_ports {store_data[22]}]
set_load -pin_load 1 [get_ports {store_data[21]}]
set_load -pin_load 1 [get_ports {store_data[22]}]
set_load -pin_load 1 [get_ports {store_data[20]}]
set_load -pin_load 1 [get_ports {store_data[19]}]
set_load -pin_load 1 [get_ports {store_data[18]}]
set_load -pin_load 1 [get_ports {store_data[17]}]
set_load -pin_load 1 [get_ports {store_data[16]}]
set_load -pin_load 1 [get_ports {store_data[15]}]
set_load -pin_load 1 [get_ports {store_data[14]}]
set_load -pin_load 1 [get_ports {store_data[13]}]
set_load -pin_load 1 [get_ports {store_data[12]}]
set_load -pin_load 1 [get_ports {store_data[11]}]
set_load -pin_load 1 [get_ports {store_data[10]}]
set_load -pin_load 1 [get_ports {store_data[9]}]
set_load -pin_load 1 [get_ports {store_data[8]}]
set_load -pin_load 1 [get_ports {store_data[7]}]
set_load -pin_load 1 [get_ports {store_data[6]}]
set_load -pin_load 1 [get_ports {store_data[5]}]
set_load -pin_load 1 [get_ports {store_data[4]}]
set_load -pin_load 1 [get_ports {store_data[3]}]
set_load -pin_load 1 [get_ports {store_data[2]}]
set_load -pin_load 1 [get_ports {store_data[1]}]
set_load -pin_load 1 [get_ports {store_data[0]}]
set_load -pin_load 1 [get_ports {pc[31]}]
set_load -pin_load 1 [get_ports {pc[30]}]
set_load -pin_load 1 [get_ports {pc[29]}]
set_load -pin_load 1 [get_ports {pc[28]}]
set_load -pin_load 1 [get_ports {pc[27]}]
set_load -pin_load 1 [get_ports {pc[26]}]
set_load -pin_load 1 [get_ports {pc[25]}]
set_load -pin_load 1 [get_ports {pc[24]}]
set_load -pin_load 1 [get_ports {pc[23]}]
set_load -pin_load 1 [get_ports {pc[22]}]
set_load -pin_load 1 [get_ports {pc[21]}]
set_load -pin_load 1 [get_ports {pc[20]}]
set_load -pin_load 1 [get_ports {pc[19]}]
set_load -pin_load 1 [get_ports {pc[18]}]
set_load -pin_load 1 [get_ports {pc[17]}]
set_load -pin_load 1 [get_ports {pc[16]}]
set_load -pin_load 1 [get_ports {pc[15]}]
set_load -pin_load 1 [get_ports {pc[14]}]
set_load -pin_load 1 [get_ports {pc[13]}]
set_load -pin_load 1 [get_ports {pc[12]}]
set_load -pin_load 1 [get_ports {pc[11]}]
set_load -pin_load 1 [get_ports {pc[10]}]
set_load -pin_load 1 [get_ports {pc[9]}]
set_load -pin_load 1 [get_ports {pc[8]}]
set_load -pin_load 1 [get_ports {pc[7]}]
set_load -pin_load 1 [get_ports {pc[6]}]
set_load -pin_load 1 [get_ports {pc[5]}]
set_load -pin_load 1 [get_ports {pc[4]}]
set_load -pin_load 1 [get_ports {pc[3]}]
set_load -pin_load 1 [get_ports {pc[2]}]
set_load -pin_load 1 [get_ports {pc[1]}]
set_load -pin_load 1 [get_ports {pc[0]}]
set_load -pin_load 1 [get_ports {addr[31]}]
set_load -pin_load 1 [get_ports {addr[30]}]
set_load -pin_load 1 [get_ports {addr[29]}]
set_load -pin_load 1 [get_ports {addr[28]}]
set_load -pin_load 1 [get_ports {addr[27]}]
set_load -pin_load 1 [get_ports {addr[26]}]
set_load -pin_load 1 [get_ports {addr[25]}]
set_load -pin_load 1 [get_ports {addr[24]}]
set_load -pin_load 1 [get_ports {addr[23]}]
set_load -pin_load 1 [get_ports {addr[22]}]
set_load -pin_load 1 [get_ports {addr[21]}]
set_load -pin_load 1 [get_ports {addr[20]}]
set_load -pin_load 1 [get_ports {addr[19]}]
set_load -pin_load 1 [get_ports {addr[18]}]
set_load -pin_load 1 [get_ports {addr[17]}]
set_load -pin_load 1 [get_ports {addr[16]}]
set_load -pin_load 1 [get_ports {addr[15]}]
set_load -pin_load 1 [get_ports {addr[14]}]
set_load -pin_load 1 [get_ports {addr[13]}]
set_load -pin_load 1 [get_ports {addr[12]}]
set_load -pin_load 1 [get_ports {addr[11]}]
set_load -pin_load 1 [get_ports {addr[10]}]
set_load -pin_load 1 [get_ports {addr[9]}]
set_load -pin_load 1 [get_ports {addr[8]}]
set_load -pin_load 1 [get_ports {addr[7]}]
set_load -pin_load 1 [get_ports {addr[6]}]
set_load -pin_load 1 [get_ports {addr[5]}]
set_load -pin_load 1 [get_ports {addr[4]}]
set_load -pin_load 1 [get_ports {addr[3]}]
set_load -pin_load 1 [get_ports {addr[2]}]
set_load -pin_load 1 [get_ports {addr[1]}]
set_load -pin_load 1 [get_ports {addr[0]}]
set_load -pin_load 1 [get_ports {store_req[3]}]
set_load -pin_load 1 [get_ports {store_req[2]}]
set_load -pin_load 1 [get_ports {store_req[1]}]
set_load -pin_load 1 [get_ports {store_req[0]}]
set_load -pin_load 1 [get_ports {load_req[3]}]
set_load -pin_load 1 [get_ports {load_req[2]}]
set_load -pin_load 1 [get_ports {load_req[1]}]
set_load -pin_load 1 [get_ports {load_req[0]}]


create_clock [get_ports clk]  -period 8 -waveform {0 4}
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk 4 [get_ports {inst[31]}]
set_input_delay -clock clk 4 [get_ports {inst[30]}]
set_input_delay -clock clk 4 [get_ports {inst[29]}]
set_input_delay -clock clk 4 [get_ports {inst[28]}]
set_input_delay -clock clk 4 [get_ports {inst[27]}]
set_input_delay -clock clk 4 [get_ports {inst[26]}]
set_input_delay -clock clk 4 [get_ports {inst[25]}]
set_input_delay -clock clk 4 [get_ports {inst[24]}]
set_input_delay -clock clk 4 [get_ports {inst[23]}]
set_input_delay -clock clk 4 [get_ports {inst[22]}]
set_input_delay -clock clk 4 [get_ports {inst[21]}]
set_input_delay -clock clk 4 [get_ports {inst[20]}]
set_input_delay -clock clk 4 [get_ports {inst[19]}]
set_input_delay -clock clk 4 [get_ports {inst[18]}]
set_input_delay -clock clk 4 [get_ports {inst[17]}]
set_input_delay -clock clk 4 [get_ports {inst[16]}]
set_input_delay -clock clk 4 [get_ports {inst[15]}]
set_input_delay -clock clk 4 [get_ports {inst[14]}]
set_input_delay -clock clk 4 [get_ports {inst[13]}]
set_input_delay -clock clk 4 [get_ports {inst[12]}]
set_input_delay -clock clk 4 [get_ports {inst[11]}]
set_input_delay -clock clk 4 [get_ports {inst[10]}]
set_input_delay -clock clk 4 [get_ports {inst[9]}]
set_input_delay -clock clk 4 [get_ports {inst[8]}]
set_input_delay -clock clk 4 [get_ports {inst[7]}]
set_input_delay -clock clk 4 [get_ports {inst[6]}]
set_input_delay -clock clk 4 [get_ports {inst[5]}]
set_input_delay -clock clk 4 [get_ports {inst[4]}]
set_input_delay -clock clk 4 [get_ports {inst[3]}]
set_input_delay -clock clk 4 [get_ports {inst[2]}]
set_input_delay -clock clk 4 [get_ports {inst[1]}]
set_input_delay -clock clk 4 [get_ports {inst[0]}]
set_input_delay -clock clk 4 [get_ports {load_data[31]}]
set_input_delay -clock clk 4 [get_ports {load_data[30]}]
set_input_delay -clock clk 4 [get_ports {load_data[29]}]
set_input_delay -clock clk 4 [get_ports {load_data[28]}]
set_input_delay -clock clk 4 [get_ports {load_data[27]}]
set_input_delay -clock clk 4 [get_ports {load_data[26]}]
set_input_delay -clock clk 4 [get_ports {load_data[25]}]
set_input_delay -clock clk 4 [get_ports {load_data[24]}]
set_input_delay -clock clk 4 [get_ports {load_data[23]}]
set_input_delay -clock clk 4 [get_ports {load_data[22]}]
set_input_delay -clock clk 4 [get_ports {load_data[21]}]
set_input_delay -clock clk 4 [get_ports {load_data[20]}]
set_input_delay -clock clk 4 [get_ports {load_data[19]}]
set_input_delay -clock clk 4 [get_ports {load_data[18]}]
set_input_delay -clock clk 4 [get_ports {load_data[17]}]
set_input_delay -clock clk 4 [get_ports {load_data[16]}]
set_input_delay -clock clk 4 [get_ports {load_data[15]}]
set_input_delay -clock clk 4 [get_ports {load_data[14]}]
set_input_delay -clock clk 4 [get_ports {load_data[13]}]
set_input_delay -clock clk 4 [get_ports {load_data[12]}]
set_input_delay -clock clk 4 [get_ports {load_data[11]}]
set_input_delay -clock clk 4 [get_ports {load_data[10]}]
set_input_delay -clock clk 4 [get_ports {load_data[9]}]
set_input_delay -clock clk 4 [get_ports {load_data[8]}]
set_input_delay -clock clk 4 [get_ports {load_data[7]}]
set_input_delay -clock clk 4 [get_ports {load_data[6]}]
set_input_delay -clock clk 4 [get_ports {load_data[5]}]
set_input_delay -clock clk 4 [get_ports {load_data[4]}]
set_input_delay -clock clk 4 [get_ports {load_data[3]}]
set_input_delay -clock clk 4 [get_ports {load_data[2]}]
set_input_delay -clock clk 4 [get_ports {load_data[1]}]
set_input_delay -clock clk 4 [get_ports {load_data[0]}]

